$schema: "https://json-schema.org/draft/2020-12/schema"
title: "showyourwork configuration"
description: "The schema for version 2 of the showyourwork configuration file"
type: object

required:
  - config_version

properties:
  config_version:
    type: integer
    description: "The version of the configuration specification"

  plugins:
    description: "A list of plugins to load"
    type: array
    items:
      type: string

  local_snakefiles:
    description: "A list of local files with additional Snakemake rules"
    type: array
    items:
      type: string

  conda:
    description: "The default conda environment YAML file"
    type: string

  static:
    description: "A list of static files and directories"
    type: array
    items:
      type: string

  dynamic:
    description: "Information about the scripts required to build the document"
    type: array
    items:
      type: object
      required:
        - script
      properties:
        script:
          type: string
        command:
          type: string
        conda:
          type: string
        input:
          type: array
          items:
            type: string
        output:
          anyOf:
            - type: string
            - type: array
              items:
                type: string

  scripts:
    description: "Rules for running scripts of different types"
    type: object
