name: tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.10"
        platform:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        exclude:
          - platform: macos-latest
            python: "3.10"
          # - platform: windows-latest
          #   python: "3.10"
    runs-on: ${{ matrix.platform }}
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Install showyourwork
        shell: bash -el {0}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"

      - name: Run tests
        shell: bash -el {0}
        run: |
          python -m pytest -v tests
